# Generated by Django 5.1.6 on 2025-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
