# Generated by Django 5.1.6 on 2025-05-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_clientes_anotaciones_historicalclientes_anotaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprendas',
            old_name='fecha_cobro',
            new_name='fecha_cobro_1',
        ),
        migrations.RenameField(
            model_name='historicalprendas',
            old_name='fecha_venta',
            new_name='fecha_venta_1',
        ),
        migrations.RenameField(
            model_name='prendas',
            old_name='fecha_cobro',
            new_name='fecha_cobro_1',
        ),
        migrations.RenameField(
            model_name='prendas',
            old_name='fecha_venta',
            new_name='fecha_venta_1',
        ),
    ]
