# Generated by Django 4.2.16 on 2025-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_clientes_alias_clientes_email_clientes_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='cobrada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
