# Generated by Django 4.2.16 on 2025-02-03 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_alter_prendas_cobrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenda', to='ingresos.clientes'),
        ),
    ]
