# Generated by Django 5.1.6 on 2025-05-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0004_rename_fecha_cobro_1_historicalprendas_fecha_cobro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprendas',
            old_name='fecha_venta',
            new_name='fecha_cobro_1',
        ),
        migrations.RenameField(
            model_name='prendas',
            old_name='fecha_venta',
            new_name='fecha_cobro_1',
        ),
    ]
