# Generated by Django 4.2.16 on 2025-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_alter_prendas_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
