# Generated by Django 5.1.6 on 2025-05-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_rename_fecha_venta_historicalprendas_fecha_cobro_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprendas',
            old_name='fecha_cobro',
            new_name='fecha_venta',
        ),
        migrations.RenameField(
            model_name='prendas',
            old_name='fecha_cobro',
            new_name='fecha_venta',
        ),
    ]
