# Generated by Django 5.1.6 on 2025-05-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0006_rename_fecha_cobro_historicalprendas_fecha_venta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalprendas',
            old_name='fecha_cobro_1',
            new_name='fecha_cobro',
        ),
        migrations.RenameField(
            model_name='prendas',
            old_name='fecha_cobro_1',
            new_name='fecha_cobro',
        ),
    ]
