# Generated by Django 4.1.12 on 2025-02-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0006_alter_prendas_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendas',
            name='fecha_cobro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
