# Generated by Django 4.1.12 on 2025-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0007_prendas_fecha_cobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
