# Generated by Django 4.1.12 on 2025-02-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('allDay', models.BooleanField(default=True)),
                ('backgroundColor', models.CharField(default='#0073b7', max_length=7)),
                ('borderColor', models.CharField(default='#0073b7', max_length=7)),
                ('text_color', models.CharField(blank=True, max_length=7)),
            ],
        ),
    ]
