# Generated by Django 5.1.6 on 2025-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='backgroundColor',
            field=models.CharField(default='#0073b7', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='borderColor',
            field=models.CharField(default='#0073b7', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
