# Generated by Django 5.1.6 on 2025-03-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprendas',
            name='cobrada',
        ),
        migrations.RemoveField(
            model_name='prendas',
            name='cobrada',
        ),
    ]
