# Generated by Django 5.1.6 on 2025-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimientos', '0002_remove_historicalprendas_cobrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprendas',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='historicalprendas',
            name='unidades_totales',
        ),
        migrations.RemoveField(
            model_name='prendas',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='prendas',
            name='unidades_totales',
        ),
        migrations.AddField(
            model_name='historicalprendas',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prendas',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
