# Generated by Django 5.1.6 on 2025-05-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimientos', '0003_remove_historicalprendas_unidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='anotaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
